### ISSUE TITLE
yacman list representation

### ISSUE THREAD

**Issue by nsheff** [databio/yacman#40]
Right now if you load up a yaml file with a list, yacman is representating that in the repr, and upon `write` as a "flow collection"

here's what the file looks like:

https://github.com/databio/hub.bulker.io/blob/8fe3ae2d5c2180bbbfec5234369d93356585e800/bulker/demo.yaml

```

manifest:
  name: demo
  version: 1.0.0
  commands:
  - command: cowsay
    docker_image: nsheff/cowsay
    docker_command: cowsay
    dockerargs: "-i"
  - command: fortune
    docker_image: nsheff/fortune
    docker_command: fortune
```

Observe:
```
 demo = yacman.YacAttMap(filepath="/home/nsheff/code/hub.bulker.io/bulker/demo.yaml")            

In [85]: demo             
Out[85]: 
manifest:
  name: demo
  version: 1.0.0
  commands: [{'command': 'cowsay', 'docker_image': 'nsheff/cowsay', 'docker_command': 'cowsay', 'dockerargs': '-i'}, {'command': 'fortune', 'docker_image': 'nsheff/fortune', 'docker_command': 'fortune'}]
```

See how the commands are collapsed into a list? This is retained if you write it out

```
demo.write("test.yaml")
```

```
manifest:
  name: demo
  version: 1.0.0
  commands: [{'command': 'cowsay', 'docker_image': 'nsheff/cowsay', 'docker_command': 'cowsay', 'dockerargs': '-i'}, {'command': 'fortune', 'docker_image': 'nsheff/fortune', 'docker_command': 'fortune'}]
```

Expected it to look  as the original.
